### ISSUE TITLE
export PATH=$PATH:/bin 실행 불가

### ISSUE THREAD

**Issue by yhshin0** [Team-42minishell/minishell#63]
`export PATH=$PATH:/bin` 실행 시 PATH에 대한 환경변수 값이 제거됨.

**Comment by yhshin0** [comment]
`PATH:/bin` 라는 키를 가진 환경변수를 찾기 때문에 값이 공백으로 치환되어 제거되는 것.

**Comment by k8440009** [comment]
subject 바깥 문제라 고민 할 필요 없는 것 같습니다.
